### ISSUE TITLE
Add Some kind of Documentation

### ISSUE THREAD

**Issue by FireRedz** [The-CJ/osu_irc.py#6]
more precisely this :
[Chat Related Commands](https://github.com/The-CJ/osu_irc.py/blob/master/osu_irc/Utils/commands.py)
[and this](https://github.com/The-CJ/osu_irc.py/blob/master/osu_irc/Classes/client.py)

**Comment by The-CJ** [comment]
new major version is out.... ee about docs, any idea how to make some good ones?

**Comment by FireRedz** [comment]
never make one, just do it the same way as discord.py one i guess

**Comment by The-CJ** [comment]
i do not have time nor do i want to make a readthedocs site, that would mean creating new subfolders just for sphinx to create the site... all functions internally are properly documented, 

Feel free to make add GitHub-Wiki-pages or so, because i will only do this if i have a huge amount of space time and small spoiler that probl. wont happen soon.

**Comment by FireRedz** [comment]
I mean you don't need to do it, I create my bot without a documentation since everything is straightforward. oh well closing this now, thanks for answering.
